In [23]:
import numpy as np
import torch

a1 = torch.randn(2, requires_grad=True)
a2 = torch.randn(2, requires_grad=True)

b = torch.add(a1, a2)
c = torch.norm(b)

c.backward(retain_graph=True)
print(a1.grad)
print(a1)

tensor([0.2833, 0.9590])
tensor([0.7412, 1.5489], requires_grad=True)


In [24]:
a1.data = torch.randn(2)
c.backward()
print(a1.grad)
print(a1)

tensor([0.5667, 1.9180])
tensor([1.1871, 1.6016], requires_grad=True)
